### ISSUE TITLE
Consider using TSDX to make the library tree-shakeable

### ISSUE THREAD

**Issue by alanrsoares** [benbowes/react-responsive-select#146]
Should be not very intrusive to replace current build/bundling with https://github.com/jaredpalmer/tsdx.

I might have a go with it and open a PR.

**Comment by benbowes** [comment]
Great please do that. I am pretty interested in tsdx

**Comment by benbowes** [comment]
Just tried out TSDX in a much simpler project https://github.com/benbowes/singleline/pull/9

It is awesome

**Comment by benbowes** [comment]
@alanrsoares I am super keen for this to happen now, having had a few goes with tsdx - thanks heaps for bringing this up!

I noticed that you have not forked this repo. This makes me think that you are not in the process of converting this over to tsdx yourself.

So I'm attempting to do this over the next few days - using the storybook preset. If you are in progress though, and want to do it let me know, otherwise I will ping you on a PR.

**Comment by alanrsoares** [comment]
Hey @benbowes. Sorry for the lack of response from my end. It's been a pretty hectic week at work. Feel free to jump it now that you more familiar with tsdx. I can definitely help reviewing the PR though.

**Comment by benbowes** [comment]
StoryBook is annoying me. As a developer I just want to know how to use a thing.

**Comment by benbowes** [comment]
Made a bit of progress in another repo on this https://github.com/benbowes/react-responsive-select-next/

New styleguidist docs here: https://benbowes.github.io/react-responsive-select-next/
Published to npm here: https://www.npmjs.com/package/react-responsive-select-next

More to do

**Comment by benbowes** [comment]
see https://github.com/benbowes/react-responsive-select/pull/150

**Comment by benbowes** [comment]
released in 6.0.0
